# Generated by Django 4.1.4 on 2023-05-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post2',
            name='int',
        ),
    ]
